# Generated by Django 5.1.4 on 2025-01-14 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255, verbose_name='Наименование отдела')),
                ('instruction_numbers', models.CharField(max_length=255, verbose_name='Номера инструкций по охране труда')),
                ('el_group', models.CharField(max_length=5, verbose_name='Группа по электробезопасности')),
                ('probation_period', models.IntegerField(verbose_name='Срок стажировки')),
                ('contract_instruction', models.CharField(max_length=255, verbose_name='Инструкции по договору подряда')),
                ('is_responsible', models.BooleanField(default=False, verbose_name='Ответственный за охрану труда')),
                ('is_electrical_staff', models.BooleanField(default=False, verbose_name='Является ли электротехническим персоналом')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.department', verbose_name='Структурное подразделение')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Профессия/Должность',
                'verbose_name_plural': 'Профессии/Должности',
            },
        ),
    ]
