# Generated by Django 4.2.18 on 2025-01-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_delete_organizations"),
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "Структурное подразделение",
                "verbose_name_plural": "Структурные подразделения",
            },
        ),
        migrations.RemoveField(
            model_name="department",
            name="created",
        ),
        migrations.RemoveField(
            model_name="department",
            name="updated",
        ),
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Действующее"),
        ),
        migrations.AddField(
            model_name="department",
            name="short_name",
            field=models.CharField(
                default="", max_length=50, verbose_name="Сокращенное наименование"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="department",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
                verbose_name="Организация",
            ),
        ),
    ]
