# Generated by Django 4.2.18 on 2025-01-18 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("importer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="imports/%Y/%m/", verbose_name="Excel файл"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("processing", "Обработка"),
                            ("completed", "Завершено"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "errors",
                    models.JSONField(blank=True, default=dict, verbose_name="Ошибки"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "processed_rows",
                    models.IntegerField(default=0, verbose_name="Обработано строк"),
                ),
                (
                    "total_rows",
                    models.IntegerField(default=0, verbose_name="Всего строк"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Тип содержимого",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия импорта",
                "verbose_name_plural": "Сессии импорта",
                "ordering": ["-created"],
            },
        ),
        migrations.DeleteModel(
            name="Importer",
        ),
    ]
