# Generated by Django 4.2.18 on 2025-01-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="clothing_size",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Размер одежды"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="height",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Рост"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_contractor",
            field=models.BooleanField(default=False, verbose_name="Договор подряда"),
        ),
        migrations.AddField(
            model_name="employee",
            name="shoe_size",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Размер обуви"
            ),
        ),
    ]
