# Generated by Django 5.1.4 on 2025-01-14 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование организации')),
                ('short_name', models.CharField(max_length=100, verbose_name='Сокращенное наименование организации')),
                ('full_name_ru', models.CharField(max_length=255, verbose_name='Полное наименование организации (рус)')),
                ('full_name_by', models.CharField(max_length=255, verbose_name='Полное наименование организации (бел)')),
                ('requisites_ru', models.TextField(verbose_name='Реквизиты организации (рус)')),
                ('requisites_by', models.TextField(verbose_name='Реквизиты организации (бел)')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование структурного подразделения')),
                ('short_name', models.CharField(max_length=100, verbose_name='Сокращенное наименование')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Структурное подразделение',
                'verbose_name_plural': 'Структурные подразделения',
            },
        ),
    ]
