# Generated by Django 4.2.18 on 2025-01-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "full_name",
                    models.CharField(
                        max_length=500, verbose_name="Полное наименование"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=250, verbose_name="Краткое наименование"
                    ),
                ),
                (
                    "name_by",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Наименование на белорусском",
                    ),
                ),
                (
                    "details_ru",
                    models.TextField(
                        blank=True, verbose_name="Дополнительная информация"
                    ),
                ),
                (
                    "details_by",
                    models.TextField(
                        blank=True,
                        verbose_name="Дополнительная информация на белорусском",
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
        migrations.DeleteModel(
            name="Organizations",
        ),
    ]
